services:
  mongo:
    image: mongo:7
    container_name: yper-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - yper-mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  yper-mongo-data:
